apiVersion: v1
kind: Endpoints
metadata:
  name: heketi-storage-endpoints
subsets:
- addresses:
  - ip: 192.168.0.20
  ports:
  - port: 1
- addresses:
  - ip: 192.168.0.24
  ports:
  - port: 1
- addresses:
  - ip: 192.168.0.34
  ports:
  - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: heketi-storage-endpoints
spec:
  ports:
  - port: 1
